# Generated by Django 6.0.5 on 2026-05-25 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghg_scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions (Fuel/Procurement)'), ('SCOPE_2', 'Scope 2 - Indirect Emissions (Electricity)'), ('SCOPE_3', 'Scope 3 - Value Chain (Business Travel)')], max_length=10)),
                ('category_label', models.CharField(help_text='e.g., Diesel Fuel, Purchased Electricity, Economy Flight', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(help_text='e.g., Liters, kWh, Gallons, Miles', max_length=50)),
                ('co2e_emissions_mt', models.DecimalField(decimal_places=4, help_text='Calculated Metric Tons of CO2e emissions', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUSPICIOUS', 'Flagged / Suspicious'), ('APPROVED', 'Approved & Locked')], default='PENDING', max_length=15)),
                ('analyst_notes', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g., STATUS_CHANGE, VALUE_EDIT, DATA_LOCK', max_length=50)),
                ('old_value', models.JSONField(blank=True, help_text='Snapshot before modification', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Snapshot after modification', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ingestion.normalizedemissionrecord')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='RawSourcePayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Export'), ('UTILITY', 'Utility Portal CSV'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(help_text='Stores the exact raw row/JSON map received from the source system')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_payloads', to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='source_payload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.rawsourcepayload'),
        ),
    ]
